// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoPfCGhxT7lMCvZ5vL45XTXfJGf_JY7M0',
    appId: '1:798221873917:web:f394d5f2c2e4ee1f10c494',
    messagingSenderId: '798221873917',
    projectId: 'fir-forminiproject',
    authDomain: 'fir-forminiproject.firebaseapp.com',
    storageBucket: 'fir-forminiproject.firebasestorage.app',
    measurementId: 'G-6QMDENJ3QL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4c90qaH3eF3gdAxj6yR_BfZDLlB7A-7Q',
    appId: '1:798221873917:android:4b50c9512540131310c494',
    messagingSenderId: '798221873917',
    projectId: 'fir-forminiproject',
    storageBucket: 'fir-forminiproject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpj0h4hEaPF1T6r362dlEthBYc7GlV__A',
    appId: '1:798221873917:ios:a70653ef78344d2f10c494',
    messagingSenderId: '798221873917',
    projectId: 'fir-forminiproject',
    storageBucket: 'fir-forminiproject.firebasestorage.app',
    iosBundleId: 'com.example.weektwo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpj0h4hEaPF1T6r362dlEthBYc7GlV__A',
    appId: '1:798221873917:ios:a70653ef78344d2f10c494',
    messagingSenderId: '798221873917',
    projectId: 'fir-forminiproject',
    storageBucket: 'fir-forminiproject.firebasestorage.app',
    iosBundleId: 'com.example.weektwo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoPfCGhxT7lMCvZ5vL45XTXfJGf_JY7M0',
    appId: '1:798221873917:web:f32f34363ba60c9010c494',
    messagingSenderId: '798221873917',
    projectId: 'fir-forminiproject',
    authDomain: 'fir-forminiproject.firebaseapp.com',
    storageBucket: 'fir-forminiproject.firebasestorage.app',
    measurementId: 'G-0JDN8D18QJ',
  );
}
